[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = '0.8.20'
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoint]
sepolia = 'https://eth-sepolia.g.alchemy.com/v2/WM8mTNBK1xYqjKTpQeItY'
dotenv = true
